# Generated by Django 4.0.4 on 2022-05-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('venue', models.CharField(max_length=350, verbose_name='Venue')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('adults_only', models.BooleanField(default=False, verbose_name='Adults_Only')),
                ('number_of_attendees', models.IntegerField(verbose_name='Number_Of_Attendees')),
            ],
        ),
    ]
